services:
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: AuthenticationTemplate.Auth.Api/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:5544
      - OTEL_SERVICE_NAME=Auth.Api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341
    depends_on:
      - mongo
      - seq
    networks:
      - internal
  
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
#    ports:
#      - "27017:27017"
    networks:
      - internal
  
  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    volumes:
      - ./seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Qwerty123_
      - SEQ_OPENTELEMETRY_ENABLED=True
    networks:
      - internal
        
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth.api
      - seq
    networks:
      - internal

networks:
  internal:
    driver: bridge
